name: Simple Build Workflow

on:
  push:
    branches:
      - master

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        run: echo "Starting build process..."

      - name: Trigger Build
        env:
          BUILD_API_URL: ${{ secrets.TS_BUILD_API }}
        run: |
          if [ -z "$BUILD_API_URL" ]; then
            echo "BUILD_API_URL secret is not set!"
            exit 1
          fi
          curl -X GET "$BUILD_API_URL"

      - name: Completion
        run: echo "Build process completed."

